# Setup
```{r setup, warning=FALSE, message=FALSE, results="hide"}
library("here") # Better structure and relative paths
library("tidyverse") # general data manipulation
conflict_prefer_all("dplyr", losers = NULL, quiet = FALSE)
here::i_am("README.txt")
```

# Load & format phenomics data
## Load data
```{r}
pheno_data <- read_delim("FamilyStudy_PhenoData_13092022.csv")
sample_data <- read_delim("FamilyStudy_Samples_13092022.csv")
```

## Format data 
```{r}
formatted_wide <- pheno_data %>% 
  pivot_wider(names_from = phenoVariable, values_from = result, id_cols = c(projectId, sourceId)) %>%  
  mutate(across(3:last_col(), ~str_replace(.x, ",", "."))) %>% # change to english decimal
  mutate(mutate(across(3:last_col(),~as.numeric(.x))))  # convert to numeric cols
```

## De duplicate measurements
```{r}
phenomics_meta_data <- formatted_wide %>% 
  group_by(sourceId) %>% 
  summarise(across(where(is.numeric), ~mean(.x, na.rm=T)))

saveRDS(object = phenomics_meta_data, file = "phenomics_meta_data.RDS")
write_tsv(phenomics_meta_data, file = "phenomics_meta_data.tsv")
```


```{r}
metadata_tibble %>% 
  inner_join(pheno_data %>% 
               filter(projectId==6) %>% 
               pivot_wider(names_from = phenoVariable, values_from = result, id_cols = c(sourceId)) )
```

